-- 作业票管理表
CREATE TABLE IF NOT EXISTS work_ticket (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ticket_no VARCHAR(50) DEFAULT NULL COMMENT '编号',
  work_location VARCHAR(200) NOT NULL COMMENT '作业位置',
  weekly_invoice_day TINYINT NOT NULL COMMENT '每周开票时间(星期几 1-7)',
  next_start_date DATE DEFAULT NULL COMMENT '下次开始时间',
  is_enabled TINYINT(1) DEFAULT 1 COMMENT '是否启用 0-否 1-是',
  approver VARCHAR(50) DEFAULT NULL COMMENT '审批人',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  is_deleted TINYINT(1) DEFAULT 0 COMMENT '是否删除 0-否 1-是',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='作业票管理表';
