CREATE TABLE IF NOT EXISTS scaffold_commission (
  id INT AUTO_INCREMENT PRIMARY KEY,
  commission_no VARCHAR(50) NOT NULL COMMENT '委托单编号',
  has_electronic TINYINT(1) DEFAULT 0 COMMENT '是否存在电子版',
  applicant_unit VARCHAR(100) NOT NULL COMMENT '申请单位',
  entry_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '录入时间',
  photo_urls TEXT COMMENT '照片URL（JSON数组）',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='架设委托记录';
